//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouchForFood.App_GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add?.
        /// </summary>
        public static string AddConfirm {
            get {
                return ResourceManager.GetString("AddConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string BillMenu_Header {
            get {
                return ResourceManager.GetString("BillMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Waiter!(Customer).
        /// </summary>
        public static string CallWaiter_Header {
            get {
                return ResourceManager.GetString("CallWaiter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesLink {
            get {
                return ResourceManager.GetString("CategoriesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Deleting....
        /// </summary>
        public static string Category_Delete {
            get {
                return ResourceManager.GetString("Category_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Manager.
        /// </summary>
        public static string Category_Header {
            get {
                return ResourceManager.GetString("Category_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category is currently active! Cannot delete it..
        /// </summary>
        public static string CategoryActiveError {
            get {
                return ResourceManager.GetString("CategoryActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category has items associated to it. It cannot be deleted.
        /// </summary>
        public static string CategoryAssociationError {
            get {
                return ResourceManager.GetString("CategoryAssociationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string CategoryBack_Link {
            get {
                return ResourceManager.GetString("CategoryBack_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this category?.
        /// </summary>
        public static string CategoryDelete_Confirm {
            get {
                return ResourceManager.GetString("CategoryDelete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category exists in a menu. It cannot be deleted.
        /// </summary>
        public static string CategoryMenuAssociationError {
            get {
                return ResourceManager.GetString("CategoryMenuAssociationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + New Category.
        /// </summary>
        public static string CategoryNew_Link {
            get {
                return ResourceManager.GetString("CategoryNew_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space for some description like sides..
        /// </summary>
        public static string CategoryTable_Desc {
            get {
                return ResourceManager.GetString("CategoryTable_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string CategoryTable_Header {
            get {
                return ResourceManager.GetString("CategoryTable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Create New Bill.
        /// </summary>
        public static string CreateBill_Link {
            get {
                return ResourceManager.GetString("CreateBill_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting the item.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been succesful deleted.
        /// </summary>
        public static string DeleteSuccesful {
            get {
                return ResourceManager.GetString("DeleteSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request for service has already been made..
        /// </summary>
        public static string DuplicateRequestError {
            get {
                return ResourceManager.GetString("DuplicateRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already exists!.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already exists!.
        /// </summary>
        public static string EmailNotUnique {
            get {
                return ResourceManager.GetString("EmailNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request.
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friendship.
        /// </summary>
        public static string FriendshipTable_Header {
            get {
                return ResourceManager.GetString("FriendshipTable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string Generic_BackToList {
            get {
                return ResourceManager.GetString("Generic_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Generic_Create {
            get {
                return ResourceManager.GetString("Generic_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Generic_Create_New {
            get {
                return ResourceManager.GetString("Generic_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Generic_Delete {
            get {
                return ResourceManager.GetString("Generic_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Generic_Details {
            get {
                return ResourceManager.GetString("Generic_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Generic_Edit {
            get {
                return ResourceManager.GetString("Generic_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Generic_Index {
            get {
                return ResourceManager.GetString("Generic_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeIndex_Title {
            get {
                return ResourceManager.GetString("HomeIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string ItemCreate_Price {
            get {
                return ResourceManager.GetString("ItemCreate_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemLink {
            get {
                return ResourceManager.GetString("ItemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item exists in a menu. It cannot be deleted.
        /// </summary>
        public static string ItemMenuAssociationError {
            get {
                return ResourceManager.GetString("ItemMenuAssociationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ItemsTable_Header {
            get {
                return ResourceManager.GetString("ItemsTable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string ItemTable_Category {
            get {
                return ResourceManager.GetString("ItemTable_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ItemTable_DeleteHeader {
            get {
                return ResourceManager.GetString("ItemTable_DeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string ItemTable_Description {
            get {
                return ResourceManager.GetString("ItemTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string ItemTable_Header {
            get {
                return ResourceManager.GetString("ItemTable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image_url.
        /// </summary>
        public static string ItemTable_ImageURL {
            get {
                return ResourceManager.GetString("ItemTable_ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata.
        /// </summary>
        public static string ItemTable_MetaData {
            get {
                return ResourceManager.GetString("ItemTable_MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string ItemTable_Name {
            get {
                return ResourceManager.GetString("ItemTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service request has already been updated somewhere else. Please refresh and try again.
        /// </summary>
        public static string LockError {
            get {
                return ResourceManager.GetString("LockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Bills.
        /// </summary>
        public static string ManageBills_Title {
            get {
                return ResourceManager.GetString("ManageBills_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string MenuActive {
            get {
                return ResourceManager.GetString("MenuActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This menu is currently active! Cannot delete it..
        /// </summary>
        public static string MenuActiveError {
            get {
                return ResourceManager.GetString("MenuActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This menu is currently active. Disactivate it before deleting it.\n.
        /// </summary>
        public static string MenuActiveWarning {
            get {
                return ResourceManager.GetString("MenuActiveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string MenuAjaxOrder_Link {
            get {
                return ResourceManager.GetString("MenuAjaxOrder_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This menu has categories associated to it. \n Are you sure you want to delete it?.
        /// </summary>
        public static string MenuAssociationWarning {
            get {
                return ResourceManager.GetString("MenuAssociationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string MenuCategory_AjaxLink {
            get {
                return ResourceManager.GetString("MenuCategory_AjaxLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string MenuCategory_Form {
            get {
                return ResourceManager.GetString("MenuCategory_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string MenuCategory_TableCategory {
            get {
                return ResourceManager.GetString("MenuCategory_TableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        public static string MenuCategory_TableMenu {
            get {
                return ResourceManager.GetString("MenuCategory_TableMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category is currently active. Disactivate it before deleting it.\n.
        /// </summary>
        public static string MenuCategoryActiveWarning {
            get {
                return ResourceManager.GetString("MenuCategoryActiveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This menu category has items associated to it. \n Are you sure you want to delete it?.
        /// </summary>
        public static string MenuCategoryAssociationWarning {
            get {
                return ResourceManager.GetString("MenuCategoryAssociationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_category.
        /// </summary>
        public static string MenuCategoryCreate_TableHeader {
            get {
                return ResourceManager.GetString("MenuCategoryCreate_TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Category.
        /// </summary>
        public static string MenuCatgeoryLink {
            get {
                return ResourceManager.GetString("MenuCatgeoryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Create New Menu.
        /// </summary>
        public static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Menu.
        /// </summary>
        public static string MenuCreate_Header {
            get {
                return ResourceManager.GetString("MenuCreate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- Create a new menu.
        /// </summary>
        public static string MenuCreate_S1 {
            get {
                return ResourceManager.GetString("MenuCreate_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- Edit a menu by clicking it.
        /// </summary>
        public static string MenuCreate_S2 {
            get {
                return ResourceManager.GetString("MenuCreate_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3- Activate a menu using checkbox.
        /// </summary>
        public static string MenuCreate_S3 {
            get {
                return ResourceManager.GetString("MenuCreate_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this menu?.
        /// </summary>
        public static string MenuDelete_Confirm {
            get {
                return ResourceManager.GetString("MenuDelete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Deleting....
        /// </summary>
        public static string MenuDelete_Header {
            get {
                return ResourceManager.GetString("MenuDelete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu is now deleted.
        /// </summary>
        public static string MenuDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("MenuDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu is now deleted.
        /// </summary>
        public static string MenuDeleteSucessMessage {
            get {
                return ResourceManager.GetString("MenuDeleteSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Categories.
        /// </summary>
        public static string MenuDetails_Categories {
            get {
                return ResourceManager.GetString("MenuDetails_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Menu.
        /// </summary>
        public static string MenuDetails_Header {
            get {
                return ResourceManager.GetString("MenuDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        public static string MenuEditTable_Header {
            get {
                return ResourceManager.GetString("MenuEditTable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the following fields to create a menu..
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Editor.
        /// </summary>
        public static string MenuIndex_Header {
            get {
                return ResourceManager.GetString("MenuIndex_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to order.
        /// </summary>
        public static string MenuItem_AjaxLink {
            get {
                return ResourceManager.GetString("MenuItem_AjaxLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this order?.
        /// </summary>
        public static string MenuItem_CancelConfirm {
            get {
                return ResourceManager.GetString("MenuItem_CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Ratings.
        /// </summary>
        public static string MenuItem_RecentRatings {
            get {
                return ResourceManager.GetString("MenuItem_RecentRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space for list of ratings pertaining to this item.
        /// </summary>
        public static string MenuItem_Space {
            get {
                return ResourceManager.GetString("MenuItem_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_item.
        /// </summary>
        public static string MenuItem_TableHeader {
            get {
                return ResourceManager.GetString("MenuItem_TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string MenuItem_TableItem {
            get {
                return ResourceManager.GetString("MenuItem_TableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_category.
        /// </summary>
        public static string MenuItem_TableMC {
            get {
                return ResourceManager.GetString("MenuItem_TableMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string MenuItem_TablePrice {
            get {
                return ResourceManager.GetString("MenuItem_TablePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This menu item is currently active! Cannot delete it..
        /// </summary>
        public static string MenuItemActiveError {
            get {
                return ResourceManager.GetString("MenuItemActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the menu item..
        /// </summary>
        public static string MenuItemCreateError {
            get {
                return ResourceManager.GetString("MenuItemCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item is now deleted.
        /// </summary>
        public static string MenuItemDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("MenuItemDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be between {2} and {1} characters long..
        /// </summary>
        public static string MenuNameErrorMessage {
            get {
                return ResourceManager.GetString("MenuNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Menu.
        /// </summary>
        public static string MenuOrder_Header {
            get {
                return ResourceManager.GetString("MenuOrder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string MenuRestaurantName {
            get {
                return ResourceManager.GetString("MenuRestaurantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string MenusLink {
            get {
                return ResourceManager.GetString("MenusLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order-User.
        /// </summary>
        public static string MenusOrderUser {
            get {
                return ResourceManager.GetString("MenusOrderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a menu.
        /// </summary>
        public static string MenuUser_Header {
            get {
                return ResourceManager.GetString("MenuUser_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Order_Accept {
            get {
                return ResourceManager.GetString("Order_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEM.
        /// </summary>
        public static string Order_DetailsItem {
            get {
                return ResourceManager.GetString("Order_DetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE.
        /// </summary>
        public static string Order_DetailsNote {
            get {
                return ResourceManager.GetString("Order_DetailsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        public static string Order_DetailsType {
            get {
                return ResourceManager.GetString("Order_DetailsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Orders.
        /// </summary>
        public static string Order_Index_Header {
            get {
                return ResourceManager.GetString("Order_Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order_status.
        /// </summary>
        public static string Order_OrderStatus {
            get {
                return ResourceManager.GetString("Order_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Order_Remove {
            get {
                return ResourceManager.GetString("Order_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order.
        /// </summary>
        public static string Order_Table {
            get {
                return ResourceManager.GetString("Order_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table #:.
        /// </summary>
        public static string Order_Table_Header {
            get {
                return ResourceManager.GetString("Order_Table_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item Name.
        /// </summary>
        public static string Order_TableMenuItemName {
            get {
                return ResourceManager.GetString("Order_TableMenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table_number.
        /// </summary>
        public static string Order_TableNumber {
            get {
                return ResourceManager.GetString("Order_TableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Item Version.
        /// </summary>
        public static string Order_TableOIVersion {
            get {
                return ResourceManager.GetString("Order_TableOIVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order version.
        /// </summary>
        public static string Order_TableOrderVersion {
            get {
                return ResourceManager.GetString("Order_TableOrderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timestamp.
        /// </summary>
        public static string Order_TableTimestamp {
            get {
                return ResourceManager.GetString("Order_TableTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string Order_TableTotal {
            get {
                return ResourceManager.GetString("Order_TableTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string Order_User {
            get {
                return ResourceManager.GetString("Order_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string Order_Version {
            get {
                return ResourceManager.GetString("Order_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiter.
        /// </summary>
        public static string Order_Waiter {
            get {
                return ResourceManager.GetString("Order_Waiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order-Admin.
        /// </summary>
        public static string OrderAminLink {
            get {
                return ResourceManager.GetString("OrderAminLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline Item.
        /// </summary>
        public static string OrderDecline_Title {
            get {
                return ResourceManager.GetString("OrderDecline_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to decline this item?.
        /// </summary>
        public static string OrderDeclineConfirm {
            get {
                return ResourceManager.GetString("OrderDeclineConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order  Total:.
        /// </summary>
        public static string OrderEdit_Total {
            get {
                return ResourceManager.GetString("OrderEdit_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item #.
        /// </summary>
        public static string OrderItem_Header {
            get {
                return ResourceManager.GetString("OrderItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_changed.
        /// </summary>
        public static string OrderItem_LastChanged {
            get {
                return ResourceManager.GetString("OrderItem_LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_item.
        /// </summary>
        public static string OrderItem_MI {
            get {
                return ResourceManager.GetString("OrderItem_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        public static string OrderItem_Note {
            get {
                return ResourceManager.GetString("OrderItem_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order_item_status.
        /// </summary>
        public static string OrderItem_Status {
            get {
                return ResourceManager.GetString("OrderItem_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order_item.
        /// </summary>
        public static string OrderItem_TableHeader {
            get {
                return ResourceManager.GetString("OrderItem_TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order.
        /// </summary>
        public static string OrderItem_TableOrder {
            get {
                return ResourceManager.GetString("OrderItem_TableOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string OrderItem_Version {
            get {
                return ResourceManager.GetString("OrderItem_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order has an item that is being processed. Cannot delete it..
        /// </summary>
        public static string OrderItemProcessingError {
            get {
                return ResourceManager.GetString("OrderItemProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order has already been updated somewhere else. Please refresh and try again.
        /// </summary>
        public static string OrderLockError {
            get {
                return ResourceManager.GetString("OrderLockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage bills.
        /// </summary>
        public static string OrderManage_Action {
            get {
                return ResourceManager.GetString("OrderManage_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        public static string OrderNumber_Header {
            get {
                return ResourceManager.GetString("OrderNumber_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status:.
        /// </summary>
        public static string OrderOS_Header {
            get {
                return ResourceManager.GetString("OrderOS_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Orders_Cancel {
            get {
                return ResourceManager.GetString("Orders_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking Status:.
        /// </summary>
        public static string Orders_CookingStatus {
            get {
                return ResourceManager.GetString("Orders_CookingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Orders_Description {
            get {
                return ResourceManager.GetString("Orders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Order.
        /// </summary>
        public static string Orders_Editing {
            get {
                return ResourceManager.GetString("Orders_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        public static string Orders_Finalize {
            get {
                return ResourceManager.GetString("Orders_Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Orders_Name {
            get {
                return ResourceManager.GetString("Orders_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string Orders_Note {
            get {
                return ResourceManager.GetString("Orders_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered by:.
        /// </summary>
        public static string Orders_OrderBy {
            get {
                return ResourceManager.GetString("Orders_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Orders_StatusMessage {
            get {
                return ResourceManager.GetString("Orders_StatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Orders_Total {
            get {
                return ResourceManager.GetString("Orders_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Order.
        /// </summary>
        public static string Orders_ViewOrder {
            get {
                return ResourceManager.GetString("Orders_ViewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your waiter today is.
        /// </summary>
        public static string Orders_WaiterGreeting {
            get {
                return ResourceManager.GetString("Orders_WaiterGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any Orders created.
        /// </summary>
        public static string OrdersNA {
            get {
                return ResourceManager.GetString("OrdersNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string OrderTime_Header {
            get {
                return ResourceManager.GetString("OrderTime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiter:.
        /// </summary>
        public static string OrderWaiter_Header {
            get {
                return ResourceManager.GetString("OrderWaiter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string Restaurant_Address {
            get {
                return ResourceManager.GetString("Restaurant_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string Restaurant_City {
            get {
                return ResourceManager.GetString("Restaurant_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurant.
        /// </summary>
        public static string Restaurant_Header {
            get {
                return ResourceManager.GetString("Restaurant_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Restaurant_Name {
            get {
                return ResourceManager.GetString("Restaurant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postal_code.
        /// </summary>
        public static string Restaurant_PC {
            get {
                return ResourceManager.GetString("Restaurant_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rating.
        /// </summary>
        public static string Restaurant_Rating {
            get {
                return ResourceManager.GetString("Restaurant_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string RestaurantAddress {
            get {
                return ResourceManager.GetString("RestaurantAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :Anonymous.
        /// </summary>
        public static string RestaurantAnonAuthor {
            get {
                return ResourceManager.GetString("RestaurantAnonAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string RestaurantCity {
            get {
                return ResourceManager.GetString("RestaurantCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string RestaurantLink {
            get {
                return ResourceManager.GetString("RestaurantLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Name.
        /// </summary>
        public static string RestaurantName {
            get {
                return ResourceManager.GetString("RestaurantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string RestaurantPostalCode {
            get {
                return ResourceManager.GetString("RestaurantPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Reviews.
        /// </summary>
        public static string RestaurantReview_Header {
            get {
                return ResourceManager.GetString("RestaurantReview_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specifiy a user and a restaurant.
        /// </summary>
        public static string RestaurantUserNotSpecifiedError {
            get {
                return ResourceManager.GetString("RestaurantUserNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the review.
        /// </summary>
        public static string Review_Create_Error {
            get {
                return ResourceManager.GetString("Review_Create_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now reviewing:.
        /// </summary>
        public static string Review_Header {
            get {
                return ResourceManager.GetString("Review_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Description.
        /// </summary>
        public static string ReviewDescription {
            get {
                return ResourceManager.GetString("ReviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Review Anonymous.
        /// </summary>
        public static string ReviewMakeAnonymous {
            get {
                return ResourceManager.GetString("ReviewMakeAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Order Item is now deleted.
        /// </summary>
        public static string ReviewOrderItemDeleted {
            get {
                return ResourceManager.GetString("ReviewOrderItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string ReviewRating {
            get {
                return ResourceManager.GetString("ReviewRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReviewVM.
        /// </summary>
        public static string ReviewVMSession {
            get {
                return ResourceManager.GetString("ReviewVMSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written By.
        /// </summary>
        public static string ReviewWrittenBy {
            get {
                return ResourceManager.GetString("ReviewWrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written On.
        /// </summary>
        public static string ReviewWrittenOn {
            get {
                return ResourceManager.GetString("ReviewWrittenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error occurred while processing your request, please try again later..
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this service request?.
        /// </summary>
        public static string Service_Request_CancelConfirm {
            get {
                return ResourceManager.GetString("Service_Request_CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Service Request.
        /// </summary>
        public static string Service_Request_CloseConfirm {
            get {
                return ResourceManager.GetString("Service_Request_CloseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this service request?.
        /// </summary>
        public static string Service_Request_DeleteConfirm {
            get {
                return ResourceManager.GetString("Service_Request_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Service Requests.
        /// </summary>
        public static string ServiceRequest_Back {
            get {
                return ResourceManager.GetString("ServiceRequest_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Waiter!.
        /// </summary>
        public static string ServiceRequest_CallW {
            get {
                return ResourceManager.GetString("ServiceRequest_CallW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Service Request.
        /// </summary>
        public static string ServiceRequest_CancelUser {
            get {
                return ResourceManager.GetString("ServiceRequest_CancelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string ServiceRequest_Comment {
            get {
                return ResourceManager.GetString("ServiceRequest_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Service Request.
        /// </summary>
        public static string ServiceRequest_Create {
            get {
                return ResourceManager.GetString("ServiceRequest_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string ServiceRequest_Created {
            get {
                return ResourceManager.GetString("ServiceRequest_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Service Request.
        /// </summary>
        public static string ServiceRequest_Delete {
            get {
                return ResourceManager.GetString("ServiceRequest_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Details.
        /// </summary>
        public static string ServiceRequest_Details {
            get {
                return ResourceManager.GetString("ServiceRequest_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Request.
        /// </summary>
        public static string ServiceRequest_Edit {
            get {
                return ResourceManager.GetString("ServiceRequest_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request(Admin/Resto).
        /// </summary>
        public static string ServiceRequest_Header {
            get {
                return ResourceManager.GetString("ServiceRequest_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Requests.
        /// </summary>
        public static string ServiceRequest_HeaderList {
            get {
                return ResourceManager.GetString("ServiceRequest_HeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant ID:.
        /// </summary>
        public static string ServiceRequest_Resaurant {
            get {
                return ResourceManager.GetString("ServiceRequest_Resaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Name:.
        /// </summary>
        public static string ServiceRequest_RestaurantName {
            get {
                return ResourceManager.GetString("ServiceRequest_RestaurantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        public static string ServiceRequest_Table {
            get {
                return ResourceManager.GetString("ServiceRequest_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request has been created!.
        /// </summary>
        public static string ServiceRequestAdminSuccess {
            get {
                return ResourceManager.GetString("ServiceRequestAdminSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table number missing! To request service through TFF please sign in at a table..
        /// </summary>
        public static string ServiceRequestClientNotAssignedTable {
            get {
                return ResourceManager.GetString("ServiceRequestClientNotAssignedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call for service has already been made for your table..
        /// </summary>
        public static string ServiceRequestDuplicateRequestClient {
            get {
                return ResourceManager.GetString("ServiceRequestDuplicateRequestClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request for service has already been made at the selected table..
        /// </summary>
        public static string ServiceRequestDuplicateRequestError {
            get {
                return ResourceManager.GetString("ServiceRequestDuplicateRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service request has already been updated somewhere else. Please refresh and try again.
        /// </summary>
        public static string ServiceRequestLockError {
            get {
                return ResourceManager.GetString("ServiceRequestLockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The waiter has been called!.
        /// </summary>
        public static string ServiceRequestSuccess {
            get {
                return ResourceManager.GetString("ServiceRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table reference cannot be left blank.
        /// </summary>
        public static string ServiceRequestTableNullError {
            get {
                return ResourceManager.GetString("ServiceRequestTableNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This side is currently active! Cannot delete it..
        /// </summary>
        public static string SideActiveWarning {
            get {
                return ResourceManager.GetString("SideActiveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string value in StrToByteArray.
        /// </summary>
        public static string StringExcpetion {
            get {
                return ResourceManager.GetString("StringExcpetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Table_Name {
            get {
                return ResourceManager.GetString("Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC Link.
        /// </summary>
        public static string Table_NFC {
            get {
                return ResourceManager.GetString("Table_NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table #.
        /// </summary>
        public static string TAble_Number {
            get {
                return ResourceManager.GetString("TAble_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Orders.
        /// </summary>
        public static string Table_Orders {
            get {
                return ResourceManager.GetString("Table_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurant.
        /// </summary>
        public static string Table_Restaurant {
            get {
                return ResourceManager.GetString("Table_Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a table. No restaurant associated to you..
        /// </summary>
        public static string TableCreateError {
            get {
                return ResourceManager.GetString("TableCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string TableLink {
            get {
                return ResourceManager.GetString("TableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table reference cannot be left blank.
        /// </summary>
        public static string TableNullError {
            get {
                return ResourceManager.GetString("TableNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch For Food User List.
        /// </summary>
        public static string TouchForFoodUserList {
            get {
                return ResourceManager.GetString("TouchForFoodUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred, please try again..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first_name.
        /// </summary>
        public static string User_FirstName {
            get {
                return ResourceManager.GetString("User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_name.
        /// </summary>
        public static string User_LastName {
            get {
                return ResourceManager.GetString("User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Orders.
        /// </summary>
        public static string User_PastOrders {
            get {
                return ResourceManager.GetString("User_PastOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Order Details.
        /// </summary>
        public static string User_PastOrdersDetails {
            get {
                return ResourceManager.GetString("User_PastOrdersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Reviews.
        /// </summary>
        public static string User_PastReviews {
            get {
                return ResourceManager.GetString("User_PastReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string User_Profile {
            get {
                return ResourceManager.GetString("User_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string User_Username {
            get {
                return ResourceManager.GetString("User_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string UserConfirmPassword {
            get {
                return ResourceManager.GetString("UserConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string UserConfirmPasswordError {
            get {
                return ResourceManager.GetString("UserConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user profile.
        /// </summary>
        public static string UserCreate {
            get {
                return ResourceManager.GetString("UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string UserCreate_ErrorMessage {
            get {
                return ResourceManager.GetString("UserCreate_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the following fields to create a user account..
        /// </summary>
        public static string UserCreate_Message {
            get {
                return ResourceManager.GetString("UserCreate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string UserCreate_Title {
            get {
                return ResourceManager.GetString("UserCreate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user profile.
        /// </summary>
        public static string UserCreateProfile {
            get {
                return ResourceManager.GetString("UserCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string UserEmailAddress {
            get {
                return ResourceManager.GetString("UserEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Image.
        /// </summary>
        public static string UserImage {
            get {
                return ResourceManager.GetString("UserImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch For Food User List.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Menus.
        /// </summary>
        public static string UserMenu_Header {
            get {
                return ResourceManager.GetString("UserMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists!.
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string UserNameError {
            get {
                return ResourceManager.GetString("UserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists!.
        /// </summary>
        public static string UserNameNotUnique {
            get {
                return ResourceManager.GetString("UserNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string UserPasswordError {
            get {
                return ResourceManager.GetString("UserPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersLink {
            get {
                return ResourceManager.GetString("UsersLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record has already been updated. Please refresh and try again.
        /// </summary>
        public static string VersioningError {
            get {
                return ResourceManager.GetString("VersioningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Touch For Food.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
