//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_category
    {
        public menu_category()
        {
            this.version = 1;
            this.menu_item = new HashSet<menu_item>();
            this.sides = new HashSet<side>();
        }
    
        public int id { get; set; }
        public int category_id { get; set; }
        public int menu_id { get; set; }
        public bool is_deleted { get; set; }
        public bool is_active { get; set; }
        public int version { get; set; }
    
        public virtual category category { get; set; }
        public virtual menu menu { get; set; }
        public virtual ICollection<menu_item> menu_item { get; set; }
        public virtual ICollection<side> sides { get; set; }
    }
}
