//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.version = 1;
            this.menu_category = new HashSet<menu_category>();
        }
    
        public int id { get; set; }
        public int resto_id { get; set; }
        public string name { get; set; }
        public bool is_active { get; set; }
        public bool is_deleted { get; set; }
        public int version { get; set; }
    
        public virtual ICollection<menu_category> menu_category { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
