//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.version = 1;
            this.bills = new HashSet<bill>();
            this.order_item = new HashSet<order_item>();
            this.reviews = new HashSet<review>();
        }
    
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> waiter_id { get; set; }
        public int version { get; set; }
        public Nullable<int> table_id { get; set; }
    
        public virtual ICollection<bill> bills { get; set; }
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual table table { get; set; }
        public virtual user user { get; set; }
        public virtual waiter waiter { get; set; }
        public virtual ICollection<review> reviews { get; set; }
    }
}
