//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public review()
        {
            this.review_order_item = new HashSet<review_order_item>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public decimal rating { get; set; }
        public bool is_anonymous { get; set; }
        public int order_id { get; set; }
        public int restaurant_id { get; set; }
    
        public virtual order order { get; set; }
        public virtual restaurant restaurant { get; set; }
        public virtual ICollection<review_order_item> review_order_item { get; set; }
        public virtual user user { get; set; }
    }
}
