//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review_order_item
    {
        public int id { get; set; }
        public Nullable<int> rating { get; set; }
        public string review_text { get; set; }
        public int order_item_id { get; set; }
        public int review_id { get; set; }
        public System.DateTime submitted_on { get; set; }
    
        public virtual order_item order_item { get; set; }
        public virtual review review { get; set; }
    }
}
