//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_request
    {
        public service_request()
        {
            this.version = 1;
        }
    
        public int id { get; set; }
        public string note { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public int version { get; set; }
        public Nullable<int> table_id { get; set; }
    
        public virtual table table { get; set; }
    }
}
