//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class touch_for_foodEntities : DbContext
    {
        public touch_for_foodEntities()
            : base("name=touch_for_foodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bill> bills { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<friendship> friendships { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<menu> menus { get; set; }
        public DbSet<menu_category> menu_category { get; set; }
        public DbSet<menu_item> menu_item { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<order_item> order_item { get; set; }
        public DbSet<restaurant> restaurants { get; set; }
        public DbSet<restaurant_user> restaurant_user { get; set; }
        public DbSet<review> reviews { get; set; }
        public DbSet<review_order_item> review_order_item { get; set; }
        public DbSet<service_request> service_request { get; set; }
        public DbSet<side> sides { get; set; }
        public DbSet<table> tables { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<waiter> waiters { get; set; }
    }
}
