//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.version = 1;
            this.friendships = new HashSet<friendship>();
            this.friendships1 = new HashSet<friendship>();
            this.orders = new HashSet<order>();
            this.restaurant_user = new HashSet<restaurant_user>();
            this.reviews = new HashSet<review>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string image_url { get; set; }
        public Nullable<int> current_table_id { get; set; }
        public int version { get; set; }
        public Nullable<int> user_role { get; set; }
    
        public virtual ICollection<friendship> friendships { get; set; }
        public virtual ICollection<friendship> friendships1 { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<restaurant_user> restaurant_user { get; set; }
        public virtual ICollection<review> reviews { get; set; }
        public virtual table table { get; set; }
    }
}
