//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchForFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class waiter
    {
        public waiter()
        {
            this.version = 1;
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> resto_id { get; set; }
        public int version { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
